#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os,sys

prog_dir = '/Users/brucelee/src/youku-lixian/'

def main():
    if len(sys.argv) < 2:
        print "Wrong arguemnt number!" 
        sys.exit(1)
    else:
        key = str(sys.argv[1])
    
    if not os.path.exists(prog_dir):
        print "program dir does not exist!"
        sys.exit(1)

    try:
        cmd = 'python ' + prog_dir + key + '.py ' + sys.argv[2]
        os.system(cmd)
    except IndexError:
        print "Not enough arguments given!"
        sys.exit(1)
    except:
        print "Error running command: %s" % (cmd)
        sys.exit(1)

if __name__ == '__main__':
    main()
