#!/usr/bin/env python
# -*- coding: utf-8 -*-

# 2014/1/11,lwldcr@gmail.com
# for uploading url text to my ftp server

import socket
from ftplib import FTP

import sys,os

def loginFtp(uname='anonymous',passwd=''):
    socket.setdefaulttimeout(10)
    print 'login to ftp...'
    ftp = FTP('raspberrypi.com')
    if not uname:
        uname = 'anonymous'

    res = ftp.login(uname,passwd)
    if res.split()[0] == '230':
        print 'login successfully.'
    else:
        print 'login error,quiting...'
        ftp.quit()
        sys.exit(1)
    return ftp

def upload(ftp, filename):
    """Upload files to ftp server."""
    if not os.path.isfile(filename):
        print "No such file: %s" % filename
    fp = open(filename,'rb')

    if not ftp:
        print "No ftp connections,quiting..."
        sys.exit(1)
    try:
        ftp.cwd('/upload')
    except:
        print "No uploading directory,quiting..."
        sys.exit(1)

    bufsize = 1024 # set buffer size
    ftp.storbinary("STOR %s" % os.path.basename(filename), fp, bufsize)
    fp.close()
    print "Upload file: %s succeeded!" % filename

def download(ftp, filename):
    """Download files from ftp server."""
    if not ftp:
        print "No ftp connections,quiting..."
        sys.exit(1)
    bufsize = 1024
    if not filename:
        print "No filename specified,quiting..."
        sys.exit(1)
    fp = open(filename, 'wb')
    ftp.cwd('/upload')
    ftp.retrbinary("RETR %s" % os.path.basename(filename), fp.write, bufsize)
    fp.close()
    print "Download file: %s succeeded!" % filename

def main():
    """main function."""
    if len(sys.argv) != 3:
        Usage()
    act = sys.argv[1]
    if act not in ['up', 'down']:
        Usage()
    ftp = loginFtp()
    if act == 'up':
        upload(ftp, sys.argv[2])
    else: 
        download(ftp, sys.argv[2])
    ftp.quit()


def Usage():
    """Usage info."""
    print 'Usage:'
    print "python %s [up|down] filename" % sys.argv[0]
    sys.exit(1)


if __name__ == '__main__':
    main()
